* Depth-dependent dynamic weakening properties

** Installation

Just copy all the codes in a single folder, and work from there; or you can add that folder to your Matlab path (see function =addpath=).

The computations involving thermal pressurisation require an additional step: you need to download the water95 package from Peter Junglas (http://www.peter-junglas.de/fh/water95/index.html), and add the correspondiong folder (should be water95/) to your path.

** What's in the box ?

All .txt files correspond to rock/mineral properties data taken from the literature (which are then fitted and/or interpolated in the computations).

All the .m files have been extensively commented, and contain a Matlab-style help file, accessible by typing =help [name of routine]=.

** Usage

In order to produce the depth profiles for all the relevant parameters, only two routines have to be used: [[profile_FH.m][profile_FH]] and [[profile_TP.m][profile_TP]].

***  Flash heating vs depth

Simply execute the routine =profile_FH=. It should generate an array of structures called fh, containing all the parameters and results. Type =help profile_FH= to display the list of computed parameters and their meaning.

Note that =profile_FH= automatically generate a series of plots.

*** Thermal pressurisation vs depth

First, edit the file [[profile_TP.m]] and choose the geological context by uncommenting one of the lines at the top of the file (either =continental_granite=, etc...). Then simply execute the script. It may take some time because computing water properties along pT paths is computationally-intensive.

Then plots can easily be generated using the arrays =depth= and the generated parameters, for instance:

#+begin_src matlab
plot(pathavgd.soap.Lstar, -depth/1e3);
xlabel('L^* (m));
ylabel('depth (km)');
#+end_src

etc.

** Troubleshooting

We have checked the codes and used them as is for the paper. Possible problems may arise if you do not have the water95 package in your matlab path, or if you haven't uncommented the relevant lines at the top of profile_TP.

The code is NOT maintained, and is guaranteed to work only for the input parameters given in the original files. Modifications may produce a weird behaviour: a typical issue might be that when using a strong geotherm (or computing things at great depths), the ambient T might be larger than Tw for flash heating !

Please do report errors if you find them in the original files. We cannot guarantee that your modifications are all legit and we do not intend to offer long-term support for the codes.

Nevertheless, we welcome all suggestions so write an email to us if you feel like sharing your ideas.

** Referencing

When using any part of the provided codes for your research, please refer to our paper:

Brantut N. and J. D. Platt, *Dynamic weakening and the depth dependence of earthquake faulting*, M.~Y. Thomas, H.~S. Bhat, and T.~M. Mitchell, eds, /Fault Zone Dynamic Processes: Evolution of Fault Properties During Seismic Rupture/, Geophys. Monogr. Ser., American Geophysical Union, Washington, DC.

(check the full reference in the published version of the paper. A pdf version of the paper can be accessed [[http://www.normalesup.org/~brantut/files/Brantut_Platt_AGUMonograph_accepted.pdf][here]]).

Of course, the codes are mostly a compendium of previously published formulae and datasets, so referring to the original papers might be needed. All the appropriate references are given both in the text of the paper, and as comments in the codes.

One might be interested in using only our fits/interpolations of permeability, porosity, thermal and yield strength properties for minerals and rocks. The text files containing the data points have been generated by copying the text from tables and/or extracting data from figures (we used the (non-free) program Graphclick to do that). These data are not ours, but please acknowledge this paper (a full reference might not be needed) when using the extracted datafiles only (it was a time-consuming job!).
